// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/5/25 上午12:43:39
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/plugins/**/*.{js,ts,mjs}","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/composables/**/*.{js,ts,mjs}","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/utils/**/*.{js,ts,mjs}","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/pages/admin/courses.vue","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/pages/admin/LearningHistoryPage.vue","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/pages/admin/MotionAnalysisPage.vue","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/pages/admin/UserManagementPage.vue","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/pages/courses/1.vue","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/pages/index.vue","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/pages/login.vue","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/UnityDanceSystem/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;